### ISSUE TITLE
Copy action isn't working.

### ISSUE THREAD

**Issue by BOVAGE** [fanifrancs/css-filters#1]
Hello @fanifrancs.

This is nice. However, the copy action isn't working even though I get the successfully copied message alert but nothing is being copied to the clipboard.

**Comment by fanifrancs** [comment]
`Okay @BOVAGE ` thanks for the feedback. I will look into it but it actually works on my mobile browser and my PC. What could really be responsible?🤔

**Comment by fanifrancs** [comment]
Google chrome.

**Comment by fanifrancs** [comment]
> > `Okay @BOVAGE ` thanks for the feedback. I will look into it but it actually works on my mobile browser and my PC. What could really be responsible?🤔
> 
> What's the name of the mobile browser you used and on which operating system?

Google chrome for android and windows

**Comment by BOVAGE** [comment]
It works on windows but it does not work on my mobile phone and I used Google Chrome on Android as well. I guess I should close the issue then

**Comment by fanifrancs** [comment]
> It works on windows but it does not work on my mobile phone and I used Google Chrome 102.0.5005.78 on Android 9 as well.

Is your mobile Chrome up to date? Please check out the repo code if you think you can help me with it. Gracias 🎉.

**Comment by BOVAGE** [comment]
> `Okay @BOVAGE ` thanks for the feedback. I will look into it but it actually works on my mobile browser and my PC. What could really be responsible?🤔

The navigator.clipboard.writeText method returns a promise and you are not waiting for its results. The which is resolved once the clipboard's contents have been updated and otherwise rejected if the caller does not have permission to write to the clipboard.

Modifying the copy function in your code to this should make it work. Try this and let's see.
```diff
-    navigator.clipboard.writeText(code);
-    alert('Code copied to clipboard.');
-    console.log(code);
+   navigator.clipboard
+      .writeText(code)
+     .then(() => {
+        alert('Code copied to clipboard.');
+      })
+     .catch(() => {
+       alert("something went wrong");
+     });
```

**Comment by fanifrancs** [comment]
All right. I'll see to that ASAP. Gracias.

**Comment by BOVAGE** [comment]
I can see you have implemented it and it's now working on my phone. I hope it's still working on your phone and other devices you tested it on. Kindly give me a feedback so as to close the issue.

**Comment by fanifrancs** [comment]
> I can see you have implemented it and it's now working on my phone. I hope it's still working on your phone and other devices you tested it on. Kindly give me a feedback so as to close the issue.
All right @BOVAGE. It still works fine on my devices and I bet it will work on any other devices. Thanks for the fix✌️.

**Comment by fanifrancs** [comment]
> I can see you have implemented it and it's now working on my phone. I hope it's still working on your phone and other devices you tested it on. Kindly give me a feedback so as to close the issue.

All right @BOVAGE. It still works fine on my devices and I bet it will work on any other devices. Thanks for the fix✌️.
